name: electrocitybd1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10
  url_launcher: ^6.2.6
  carousel_slider: ^4.2.1
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  badges: ^3.1.2
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.11
  lottie: ^3.1.0
  connectivity_plus: ^5.0.2
  fluttertoast: ^8.2.5
  get: ^4.6.6
  animated_text_kit: ^4.2.2
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  flutter_local_notifications: ^16.3.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.0.0
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  table_calendar: ^3.1.1
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  permission_handler: ^11.3.0
  device_info_plus: ^10.1.0
  package_info_plus: 9.0.0
  flutter_slidable: ^3.0.1
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  dio: ^5.4.0
  logger: ^2.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  awesome_dialog: ^3.1.0
  file_picker: ^6.1.1
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Products/
    - assets/Brand Logo/
    - assets/Hero banner logos/
    - assets/Deals of the Day/
    - assets/flash/
    - assets/data/products.json