version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: electrocitybd-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: electrocitybd
      MYSQL_USER: electrocity
      MYSQL_PASSWORD: electrocity123
      TZ: Asia/Dhaka
    ports:
      - "3306:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql:ro
